# Generated by Django 2.2.12 on 2020-07-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_userlibrary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraphs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.CharField(max_length=200)),
                ('p2', models.CharField(max_length=200)),
                ('p3', models.CharField(max_length=200)),
                ('p4', models.CharField(max_length=200)),
            ],
        ),
    ]
