# Generated by Django 2.2.12 on 2020-07-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_paragraphs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraphs',
            name='p4',
            field=models.TextField(default='-'),
        ),
    ]
