# Generated by Django 2.2.12 on 2020-07-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200706_1657'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paragraphs',
            new_name='Paragraph',
        ),
    ]
