# Generated by Django 2.2.12 on 2020-07-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20200706_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='paragraph',
            name='name',
            field=models.TextField(default='-'),
        ),
    ]
