# Generated by Django 2.2.12 on 2020-07-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_paragraph_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph',
            old_name='p1',
            new_name='pt',
        ),
    ]
