# Generated by Django 2.2.12 on 2020-07-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20200706_1815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paragraph',
        ),
    ]
