# Generated by Django 2.2.12 on 2020-09-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_delete_paragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='image',
            field=models.FileField(upload_to='ebooks/'),
        ),
    ]
