# Generated by Django 2.2.12 on 2020-09-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20200909_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='image',
            field=models.FileField(upload_to='exercisedetail.html/'),
        ),
    ]
