# Generated by Django 2.2.12 on 2020-10-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20200909_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='chapters',
            field=models.FileField(default='', upload_to='chapters/'),
            preserve_default=False,
        ),
    ]
